require("config.lazy")
require("options")
require("pluginConf.lspConf")
require("pluginConf.treesitterConf")
require("pluginConf.lualineConf")
require("pluginConf.telescopeConf")
require("pluginConf.alphaConf")
require("pluginConf.nvimsurroundConf")
require("pluginConf.treesjConf")
require("keymaps")

